Use packaging instead of distutils for version handling
distutils.LooseVersion has this bug:

   LooseVersion("1.0.a.0") < LooseVersion("1.0.0")

   TypeError: '<' not supported between instances of 'str' and 'int'